# Generated by Django 2.1 on 2018-08-28 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20180825_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_Firstname', models.CharField(max_length=10)),
                ('student_Lastname', models.CharField(max_length=10)),
                ('student_rollno', models.IntegerField(default=0)),
                ('student_phoneno', models.IntegerField(default=0)),
                ('student_emailid', models.CharField(max_length=30)),
                ('student_dob', models.DateField(verbose_name='date published')),
                ('student_address', models.CharField(max_length=100)),
                ('student_about', models.CharField(max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
