# Generated by Django 2.1 on 2018-08-28 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20180828_0549'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_title', models.CharField(max_length=10)),
                ('s_Fname', models.CharField(max_length=10)),
                ('s_Lname', models.CharField(max_length=10)),
                ('s_pno', models.IntegerField(default=0)),
                ('s_emailid', models.CharField(max_length=30)),
                ('s_dob', models.DateField(verbose_name='date published')),
                ('s_addr', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='studentdata',
        ),
    ]
